### ISSUE TITLE
Update the help command response to the new UG

### ISSUE THREAD

**Issue by tysng** [AY1920S1-CS2103T-F14-4/main#126]
<img width="659" alt="Screenshot 2019-10-30 at 12 08 50 PM" src="https://user-images.githubusercontent.com/42670338/67828351-0d22a900-fb0e-11e9-92ae-647486c645a3.png">

**Comment by junnbang** [comment]
solved

**Comment by tysng** [comment]
Maybe you want to link the PR to the issues that you have closed? For better tracking purposes.

**Comment by junnbang** [comment]
Refer to PR #137 .
