### ISSUE TITLE
UI: Ongoing and Incomplete section doesn't show the current Task ID

### ISSUE THREAD

**Issue by tysng** [AY1920S1-CS2103T-F14-4/main#134]
Both has Task ID 1? This disables any task related operations.
<img width="603" alt="Screenshot 2019-10-30 at 12 38 01 PM" src="https://user-images.githubusercontent.com/42670338/67829440-1f064b00-fb12-11e9-95eb-5d9ab689f576.png">

**Comment by ArgVampir** [comment]
The number at the front represent the number order of the list. I can add in a Task ID into the card without making it confusing
