### ISSUE TITLE
Edit command doesn't work as expected

### ISSUE THREAD

**Issue by tysng** [AY1920S1-CS2103T-F14-4/main#135]
Steps to Reproduce:
* `addT g/test c/1 dt/31/10/2019` responds with `New task added:  Task ID: 6 Goods: test Date: 31/10/2019 Delivery Person: UNASSIGNED Duration: NOT ALLOCATED Status: INCOMPLETE`
* `editT 6 g/changed` responds with `Invalid command format! 
edit: Edits the details of the person identified by the index number used in the displayed person list. Existing values will be overwritten by the input values.
Parameters: INDEX (must be a positive integer) [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [tt/TAG]...
Example: edit 1 p/91234567 e/johndoe@example.com`
* The above error message persists with more presses on the send button
* The task list is not updated either, see screenshot
<img width="1259" alt="Screenshot 2019-10-30 at 12 45 26 PM" src="https://user-images.githubusercontent.com/42670338/67829767-4ad60080-fb13-11e9-85dc-a27725ab284f.png">

**Comment by junnbang** [comment]
wrong command used, I will remove the edit command in the incoming commit.

**Comment by junnbang** [comment]
solved

**Comment by junnbang** [comment]
Refer to PR #137 .
