### ISSUE TITLE
UG: Reorganize the content page for better presentation

### ISSUE THREAD

**Issue by tysng** [AY1920S1-CS2103T-F14-4/main#142]
Now we have 20 features all nested under one section, we should split them into more sections.

<img width="531" alt="Screenshot 2019-10-31 at 3 28 03 PM" src="https://user-images.githubusercontent.com/42670338/67927238-0de13b00-fbf3-11e9-9fc5-56d7722ec618.png">

**Comment by junnbang** [comment]
done
